# Generated by Django 2.2.10 on 2020-02-22 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('channels', models.ManyToManyField(blank=True, to='shows.Channel')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows.Show')),
            ],
            options={
                'abstract': False,
                'unique_together': {('show', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True)),
                ('air_date', models.DateTimeField(blank=True, null=True)),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('video', models.URLField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='shows.Series')),
            ],
            options={
                'abstract': False,
                'unique_together': {('series', 'number')},
            },
        ),
    ]
