# Generated by Django 2.0.13 on 2020-02-20 21:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', max_length=256, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', max_length=256, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('video', models.URLField()),
                ('air_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', max_length=256, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('channels', models.ManyToManyField(to='shows.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', max_length=256, unique=True)),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='series',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='shows.Series'),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('show', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('series', 'number')},
        ),
    ]
