# Generated by Django 2.0.13 on 2020-02-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='series',
            name='title',
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
