# Generated by Django 2.0.13 on 2020-02-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20200220_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
    ]
