# Generated by Django 2.2.10 on 2020-02-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20200220_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='slug',
        ),
        migrations.AddField(
            model_name='series',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
